# -*- coding: utf-8 -*-
"""Startup Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PNuFrnYDfVdgaCNP24niZEtyM_sBfrfk
"""

import pandas as pd
import numpy as np


from io import StringIO
import requests

# Visualisation libraries
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.offline as pyo



import re

# Disable warnings 
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount("/content/drive")

data=pd.read_csv("/content/drive/MyDrive/investments_VC.csv",encoding = 'unicode_escape')

df= data.copy()

df.shape

df.columns

data.info()

"""## **Problems**

1-null values in all col

2-name col is full of nan

3-in total funding col nan value is represented by '-'

4-no need of seperate round col

5-category_list col values are not in appropriate manner

6-date cpl has null value and incorrect data type

7-round a to round g too many 0 values and incorrect data tpye

8-no need of founded_month col

9-founded_quarter col must carry the quarter number
"""

df=df.dropna(how='any', subset=['name'])

df['category_list'].replace(to_replace = r"\W",value=',',regex= True,inplace= True)

df['category_list'].replace(to_replace = r'^,',value='',regex= True,inplace= True)
df['category_list'].replace(to_replace = r'E,Commerce',value='E-Commerce',regex= True,inplace= True)

df = pd.melt(df,id_vars=['permalink', 'name', 'homepage_url', 'category_list', ' market ',
       ' funding_total_usd ', 'status', 'country_code', 'state_code', 'region',
       'city', 'funding_rounds', 'founded_at', 'founded_month',
       'founded_quarter', 'founded_year', 'first_funding_at',
       'last_funding_at', 'seed', 'venture', 'equity_crowdfunding',
       'undisclosed', 'convertible_note', 'debt_financing', 'angel', 'grant',
       'private_equity', 'post_ipo_equity', 'post_ipo_debt',
       'secondary_market', 'product_crowdfunding'],var_name = 'gen_funding_round',value_name='funding_amount')

df = pd.melt(df,id_vars=['permalink', 'name', 'homepage_url', 'category_list', ' market ',
       ' funding_total_usd ', 'status', 'country_code', 'state_code', 'region',
       'city', 'funding_rounds', 'founded_at', 'founded_month',
       'founded_quarter', 'founded_year', 'first_funding_at',
       'last_funding_at', 'gen_funding_round','funding_amount'],var_name = 'invest_round_type',value_name='amount_given')

df=df[df['funding_amount']!=0.0]

df=df[df['amount_given']!=0.0]

df.shape

df['invest_round_type'].value_counts().plot(kind='bar')

"""## vanture capitalist invested in most of the startups"""

df['status'].value_counts()

"""## closed startup is less so startup have created employement"""

sns.relplot(x='funding_rounds',y='amount_given',hue='status',data=df)

"""possibility of closing down is high if funding is not managed.

Once survived to get funded, makes easy to get funding from investers.

and after geting more than 7 time of funding the startup dosen't colse down at all but may a possibility of getting acquired (selling of the company) is there.
"""

plt.subplots(figsize=(12,5))
sns.distplot(df['amount_given'],hist=False,label='Specialized Investment')
sns.distplot(df['funding_amount'],hist=False,label='General Round Funding')
plt.xlabel('Investment')
plt.show()



"""## Specialized Investment like venturi, seed, equity are more effictivly provides funding to the startups over General Investment round"""

x=df[' market '].value_counts().reset_index()
trace = go.Bar(x=x['index'],y=x[' market '])
data=[trace]
layout = go.Layout(title = 'Startup Markets',xaxis={'title':'Market_Zone'},yaxis={'title':'Count'})
fig = go.Figure(data=data,layout=layout)
pyo.iplot(fig)

"""## World Wide successful startup markets"""

df[df['founded_year'].isna()]

df.drop(columns=['founded_at','founded_month'],inplace=True)

df.fillna(0)

df['founded_year']=pd.to_datetime(df['founded_year'])

try:
    df['first_funding_at']=pd.to_datetime(df['first_funding_at'])
except:
    pass

df['last_funding_at']=pd.to_datetime(df['last_funding_at'])

df['amount_given']=df['amount_given'].astype(int)

df['funding_amount']=df['funding_amount'].astype(int)

dft=df[df['name'].duplicated()]

dft.shape

dft.head()

dft['country_code'].value_counts().head(10)

"""## Top 10 Countries Based on Number Of Startups Established"""

ddf=df.groupby('invest_round_type').sum().reset_index()

ddf

dft[' market '].value_counts().head(30).plot(kind='bar')

def tell_country(a): ## tells country related information of startups
    df_c=dft[dft['country_code']==a]
    plt.subplot(211)
    df_c['city'].value_counts().head(10).plot(kind='pie',figsize=(10,20),autopct='%1.1f%%')
    plt.subplot(212)
    df_c[' market '].value_counts().head(30).plot(kind='bar')

tell_country('IND')

tell_country('USA')

x=dft[dft['homepage_url'].isnull()==False]

stri = []
for i in x['homepage_url']:
    stri.append(i)

l = len(stri)
i = 0
e = []
while i < l:
    y = stri[i].split('.')[len(stri[i].split('.'))-1]
    if ('/' in y == True):
        e.append(y.split('/')[0])
    else:
        e.append(y)
        
    i=i+1
    
x['domain']=e

x['domain'].replace(to_replace = r'^com[/w/.-]',value='com',regex= True,inplace=True)

x['domain'].value_counts().head(5).plot(kind='bar')

"""## Most of the startups preffers .com domains"""

dft['founded_quarter'].replace(to_replace = r'^[\d\d\d\d.-]+',value='',regex= True,inplace = True)

sns.catplot(x='founded_quarter',hue='status',kind='count', data=dft)

"""## first quarter is most important for startups"""